[SomePeripheralsConfig]
	#MAY BREAK SOMETHING. if true, will automatically remove massless ships if they appear.
	AUTOREMOVE_MASSLESS_SHIPS = true

	[SomePeripheralsConfig.ServerToolgunSettings]
		#Reload the game for change to take the effect.
		#Range: 512 ~ 1000000
		SCHEMATIC_PACKET_PART_SIZE = 30000
		#
		#Range: 1.0 ~ 1.7976931348623157E308
		MAX_RAYCAST_DISTANCE = 100.0
		#Number of connected ships a player can copy in one request. <=0 for unlimited.
		#Range: > -2147483648
		MAX_SHIPS_ALLOWED_TO_COPY = -1
	[SomePeripheralsConfig.Schematics]
		#
		#Range: 0 ~ 20000
		TIMEOUT_TIME = 50
	[SomePeripheralsConfig.Permissions]
		#DO NOT CHANGE
		ALWAYS_ALLOWED = ""
		#
		#Range: 0 ~ 4
		VMOD_TOOLGUN_PERMISSION_LEVEL = 2
		#
		#Range: 0 ~ 4
		VMOD_COMMANDS_PERMISSION_LEVEL = 2
		#
		#Range: 0 ~ 4
		VMOD_OP_COMMANDS_PERMISSION_LEVEL = 4
		#DO NOT CHANGE
		ALWAYS_DISALLOWED = ""
